#include "maingamepage.h"
#include <QCoreApplication>
#include <QDir>
#include <QFileInfo>
#include <QGraphicsView>
#include <QGraphicsScene>
#include <QGraphicsRectItem>
#include <QGraphicsSimpleTextItem>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QLabel>
#include <QPushButton>
#include <QMessageBox>
#include <QResizeEvent>
#include <QPainter>
#include <QFont>
#include <QPen>
#include <QBrush>
#include <QLinearGradient>
#include <QDebug>
